# Site settings
title: "docteurklein's tentative to write stuff"
description: "Thoughts on programming"
baseurl: ""
url: "http://docteurklein.github.io"
twitter_username: docteur_klein
github_username:  docteurklein
disqus_username:  docteurklein

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments

gems:
  - jekyll-mentions
  - jekyll-sitemap
